Repository zxing-js/library, pull requests merged in 2018-07, with the labels that each got.

#61 Remove const from enum BarcodeFormat
  src/core/BarcodeFormat.ts
Labels: P1, enhancement

#60 Fix POSSIBLE_FORMATS hint support
  src/core/MultiFormatReader.ts
  src/core/oned/MultiFormatOneDReader.ts
  src/core/oned/MultiFormatUPCEANReader.ts
  tsconfig.json
Labels: P0, enhancement

#75 README: run spellchecker
  CONTRIBUTING.md
  README.md
Labels: P0, docs, enhancement
