Repository zxing-js/library, pull requests merged in 2018-11, with the labels that each got.

#103 chore: only Node.js 8.9.0 and newer is supported
  package.json
Labels: enhancement, plat: node.js

#102 ci: test Node.js 8, 10 and 11
  .travis.yml
Labels: enhancement, plat: node.js, tests

#104 ci: use yarn cache and cache node_modules
  .travis.yml
Labels: enhancement, tests

#101 Fixed `rotate()` method for using TRY_HARDER
  src/browser/HTMLCanvasElementLuminanceSource.ts
Labels: fix

#99 Docs camera example - select input if available
  docs/examples/barcode-camera/index.html
  docs/examples/qr-camera/index.html
Labels: docs, fix

#98 Free Fire - Patch 3
  package.json
  src/browser/BrowserCodeReader.ts
  src/browser/BrowserSvgCodeWriter.ts
  src/browser/HTMLCanvasElementLuminanceSource.ts
  webpack.config.js
Labels: fix
