Repository zxing-js/library, pull requests merged in 2018-06, with the labels that each got.

#43 Updating dev branch
  README.md
Labels: housekeeping

#47 Add yarn lock
  yarn.lock
Labels: P0, fix, housekeeping

#48 Release v0.5.1
  README.md
  package.json
  yarn.lock
Labels: P0, enhancement

#50 upgrade to webpack 4
  .gitignore
  karma.conf.js
  package-lock.json
  package.json
  webpack.config.js
  webpack.config.test.js
  yarn.lock
Labels: P1, enhancement

#51 Feature/test suite up
  .gitignore
  .travis.yml
  .vscode/settings.json
  package-lock.json
  package.json
  src/test.js
  tsconfig.json
  webpack.config.test.js
Labels: P1, enhancement, tests

#56 Moke drawing canvas related code protected so that it can be extended…
  src/browser/BrowserCodeReader.ts
Labels: P0, enhancement

#62 master update
  package.json
Labels: housekeeping

#58 Code39 reading support
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  package-lock.json
  src/core/oned/Code39Reader.ts
  src/core/oned/MultiFormatOneDReader.ts
  src/index.ts
  src/test/core/oned/Code39BlackBox1.spec.ts
  src/test/core/oned/Code39BlackBox3.spec.ts
  src/test/core/oned/Code39ExtendedBlackBox2.spec.ts
  src/test/core/oned/Code39ExtendedMode.spec.ts
  src/test/core/resources/blackbox/code39-1/1.png
  src/test/core/resources/blackbox/code39-1/1.txt
  src/test/core/resources/blackbox/code39-1/2.png
  src/test/core/resources/blackbox/code39-1/2.txt
  src/test/core/resources/blackbox/code39-1/3.png
  src/test/core/resources/blackbox/code39-1/3.txt
  src/test/core/resources/blackbox/code39-1/4.png
  src/test/core/resources/blackbox/code39-1/4.txt
  src/test/core/resources/blackbox/code39-2/1.png
  src/test/core/resources/blackbox/code39-2/1.txt
  src/test/core/resources/blackbox/code39-2/2.png
  src/test/core/resources/blackbox/code39-2/2.txt
  src/test/core/resources/blackbox/code39-3/01.png
  src/test/core/resources/blackbox/code39-3/01.txt
  src/test/core/resources/blackbox/code39-3/02.png
  src/test/core/resources/blackbox/code39-3/02.txt
  src/test/core/resources/blackbox/code39-3/03.png
  src/test/core/resources/blackbox/code39-3/03.txt
  src/test/core/resources/blackbox/code39-3/04.png
  src/test/core/resources/blackbox/code39-3/04.txt
  src/test/core/resources/blackbox/code39-3/05.png
  src/test/core/resources/blackbox/code39-3/05.txt
  src/test/core/resources/blackbox/code39-3/06.png
  src/test/core/resources/blackbox/code39-3/06.txt
  src/test/core/resources/blackbox/code39-3/07.png
  src/test/core/resources/blackbox/code39-3/07.txt
  src/test/core/resources/blackbox/code39-3/08.png
  src/test/core/resources/blackbox/code39-3/08.txt
  src/test/core/resources/blackbox/code39-3/09.png
  src/test/core/resources/blackbox/code39-3/09.txt
  src/test/core/resources/blackbox/code39-3/10.png
  src/test/core/resources/blackbox/code39-3/10.txt
  src/test/core/resources/blackbox/code39-3/11.png
  src/test/core/resources/blackbox/code39-3/11.txt
  src/test/core/resources/blackbox/code39-3/12.png
  src/test/core/resources/blackbox/code39-3/12.txt
  src/test/core/resources/blackbox/code39-3/13.png
  src/test/core/resources/blackbox/code39-3/13.txt
  src/test/core/resources/blackbox/code39-3/14.png
  src/test/core/resources/blackbox/code39-3/14.txt
  src/test/core/resources/blackbox/code39-3/15.png
  src/test/core/resources/blackbox/code39-3/15.txt
  src/test/core/resources/blackbox/code39-3/16.png
  src/test/core/resources/blackbox/code39-3/16.txt
  src/test/core/resources/blackbox/code39-3/17.png
  src/test/core/resources/blackbox/code39-3/17.txt
  webpack.config.test.js
Labels: P0, barcode 1d, enhancement
