Repository zxing-js/library, pull requests merged in 2019-07, with the labels that each got.

#183 Fix most occurences of `IndexSizeError` inside firefox
  src/browser/BrowserCodeReader.ts
Labels: enhancement

#190 [Documentation] Integrate continuous video scanning example.
  docs/examples/qr-camera/index.html
Labels: enhancement

#198 Feature/new device selection api
  docs/examples/barcode-camera/index.html
  docs/examples/multi-camera/index.html
  docs/examples/qr-camera/index.html
  src/browser/BrowserCodeReader.ts
Labels: enhancement

#199 Release/v0.15.0
  .travis.yml
  docs/examples/barcode-camera/index.html
  docs/examples/multi-camera/index.html
  docs/examples/multi-image/index.html
  docs/examples/qr-camera/index.html
  docs/examples/qr-image/index.html
  docs/examples/qr-svg-writer/index.html
  docs/examples/qr-video/index.html
  package-lock.json
  package.json
  src/browser/BrowserCodeReader.ts
Labels: release

#202 Bugfix/new methods visibility
  src/browser/BrowserCodeReader.ts
  src/browser/BrowserMultiFormatReader.ts
Labels: enhancement, fix

#204 Release/v0.15.1
  src/browser/BrowserCodeReader.ts
  src/browser/BrowserMultiFormatReader.ts
  src/browser/VideoInputDevice.ts
Labels: release
