Repository zxing-js/library, pull requests merged in 2019-05, with the labels that each got.

#158 Fixes TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
  src/browser/BrowserCodeReader.ts
Labels: merge ready

#146 Update version of `ts-custom-error` to 3.0.0
  package.json
Labels: merge ready

#162 Release/v0.12.4
  package.json
  src/browser/BrowserCodeReader.ts
Labels: P0, release

#120 [WIP] Port RSS Expanded Reader
  src/core/oned/rss/expanded/BitArrayBuilder.ts
  src/core/oned/rss/expanded/ExpandedPair.ts
  src/core/oned/rss/expanded/ExpandedRow.ts
  src/core/oned/rss/expanded/RSSExpandedReader.ts
  src/core/oned/rss/expanded/decoders/AI013103decoder.ts
  src/core/oned/rss/expanded/decoders/AI01320xDecoder.ts
  src/core/oned/rss/expanded/decoders/AI01392xDecoder.ts
  src/core/oned/rss/expanded/decoders/AI01393xDecoder.ts
  src/core/oned/rss/expanded/decoders/AI013x0x1xDecoder.ts
  src/core/oned/rss/expanded/decoders/AI013x0xDecoder.ts
  src/core/oned/rss/expanded/decoders/AI01AndOtherAIs.ts
  src/core/oned/rss/expanded/decoders/AI01decoder.ts
  src/core/oned/rss/expanded/decoders/AI01weightDecoder.ts
  src/core/oned/rss/expanded/decoders/AbstractExpandedDecoder.ts
  src/core/oned/rss/expanded/decoders/AnyAIDecoder.ts
  src/core/oned/rss/expanded/decoders/BlockParsedResult.ts
  src/core/oned/rss/expanded/decoders/CurrentParsingState.ts
  src/core/oned/rss/expanded/decoders/DecodedChar.ts
  src/core/oned/rss/expanded/decoders/DecodedInformation.ts
  src/core/oned/rss/expanded/decoders/DecodedNumeric.ts
  src/core/oned/rss/expanded/decoders/DecodedObject.ts
  src/core/oned/rss/expanded/decoders/FieldParser.ts
  src/core/oned/rss/expanded/decoders/GeneralAppIdDecoder.ts
  src/core/util/StringBuilder.ts
  src/index.ts
Labels: P2, barcode 1d, enhancement, help wanted

#168 v0.13.0 - Hell disco
  package.json
  src/browser/BrowserCodeReader.ts
  src/browser/VideoInputDevice.ts
Labels: enhancement, plat: browser, release
